#!/usr/bin/env python

import rospy

import abstract_map_ros as amr
from abstract_map_lib import visual


def main():
    """Initialise the node, and run its own internal spin method"""
    rospy.init_node('abstract_map_ros')
    abstract_map_node = amr.AbstractMapNode()
    rospy.sleep(3)  # Deal with the trash that is move_base...
    abstract_map_node.spin()


if __name__ == '__main__':
    main()
