#!/usr/bin/env python

import rospy

import abstract_map_ros as amr


def main():
    rospy.init_node('abstract_map_ros')
    abstractmap_node = amr.AbstractMapNode()
    rospy.spin()


if __name__ == '__main__':
    main()
