#!/usr/bin/env python

import cPickle as pickle
import rospy

import std_msgs.msg as std_msgs

import tag_interpreter as ti


def main():
    # Initialise the node to do the one shot latched publishing
    rospy.init_node('hierarchy_publisher')
    hierarchy_filename = rospy.get_param('hierarchy_file',
                                         ti.defaultHierarchyFilename())
    pub = rospy.Publisher(ti.DEFAULT_HIERARCHY_TOPIC,
                          std_msgs.String,
                          queue_size=1,
                          latch=True)

    # Attempt to load the hierarchy from file
    h = ti.loadHierarchy(hierarchy_filename)

    # Fire the one shot publishing, then keep the node spining
    pub.publish(std_msgs.String(data=pickle.dumps(h)))
    rospy.spin()


if __name__ == '__main__':
    main()
