#!/usr/bin/env python

import rospy

import abstract_map_visualiser as amv


def main():
    """Initialiser the visualiser node, and spin waiting for msgs"""
    rospy.init_node('abstract_map_visualiser')
    abstract_map_vis = amv.VisualiserNode()
    abstract_map_vis.spin()


if __name__ == '__main__':
    main()
