title: Abstract Map
description: A Python implementation of the spring-dynamics based abstract map used in "Robot Navigation in Unseen Spaces using an Abstract Map"
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
